blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a question
    url: https://github.com/kalviumcommunity/S68_MayurKSetty_Capstone_TerraQuest/discussions
    about: Ask general questions or start a discussion